const {
    command,
    query,
    subscription,
} = require('./apiFactory');

function createSessionCatalog(ops) {
    return {
        reportRendererFatalError: command((payload) => ops.invoke('renderer:fatal-error', payload)),
        getAgents: query(() => ops.invoke('get-agents')),
        getAgentConfig: query((agentId) => ops.invoke('get-agent-config', agentId)),
        saveAgentConfig: query((agentId, config) => ops.invoke('save-agent-config', agentId, config)),
        updateAgentConfig: query((agentId, updates) => ops.invoke('update-agent-config', agentId, updates)),
        selectAvatar: query(() => ops.invoke('select-avatar')),
        saveAvatar: query((agentId, avatarData) => ops.invoke('save-avatar', agentId, avatarData)),
        createAgent: query((agentName, initialConfig) => ops.invoke('create-agent', agentName, initialConfig)),
        deleteAgent: query((agentId) => ops.invoke('delete-agent', agentId)),
        getActiveSystemPrompt: query((agentId) => ops.invoke('get-active-system-prompt', agentId)),
        getAgentTopics: query((agentId) => ops.invoke('get-agent-topics', agentId)),
        createNewTopicForAgent: query((agentId, topicName, isBranch, locked) => ops.invoke('create-new-topic-for-agent', agentId, topicName, isBranch, locked)),
        saveAgentTopicTitle: query((agentId, topicId, newTitle) => ops.invoke('save-agent-topic-title', agentId, topicId, newTitle)),
        deleteTopic: query((agentId, topicId) => ops.invoke('delete-topic', agentId, topicId)),
        getUnreadTopicCounts: query(() => ops.invoke('get-unread-topic-counts')),
        toggleTopicLock: query((agentId, topicId) => ops.invoke('toggle-topic-lock', agentId, topicId)),
        setTopicUnread: query((agentId, topicId, unread) => ops.invoke('set-topic-unread', agentId, topicId, unread)),
        getChatHistory: query((agentId, topicId) => ops.invoke('get-chat-history', agentId, topicId)),
        saveChatHistory: query((agentId, topicId, history) => ops.invoke('save-chat-history', agentId, topicId, history)),
        getOriginalMessageContent: query((itemId, itemType, topicId, messageId) => ops.invoke('get-original-message-content', itemId, itemType, topicId, messageId)),
        handleFilePaste: query((agentId, topicId, fileData) => ops.invoke('handle-file-paste', agentId, topicId, fileData)),
        selectFilesToSend: query((agentId, topicId) => ops.invoke('select-files-to-send', agentId, topicId)),
        getFileAsBase64: query((filePath) => ops.invoke('get-file-as-base64', filePath)),
        getTextContent: query((filePath, fileType) => ops.invoke('get-text-content', filePath, fileType)),
        handleTextPasteAsFile: query((agentId, topicId, textContent) => ops.invoke('handle-text-paste-as-file', agentId, topicId, textContent)),
        handleFileDrop: query((agentId, topicId, droppedFilesData) => ops.invoke('handle-file-drop', agentId, topicId, droppedFilesData)),
        sendToVCP: query((request) => ops.invoke('send-to-vcp', request)),
        generateFollowUps: query((payload) => ops.invoke('generate-follow-ups', payload)),
        generateTopicTitle: query((payload) => ops.invoke('generate-topic-title', payload)),
        onVCPStreamEvent: subscription(ops.subscribe('vcp-stream-event', (_event, eventData) => eventData)),
        interruptVcpRequest: query((request) => ops.invoke('interrupt-vcp-request', request)),
        exportTopicAsMarkdown: query((exportData) => ops.invoke('export-topic-as-markdown', exportData)),
        getEmoticonLibrary: query(() => ops.invoke('get-emoticon-library')),
        listEmoticonLibrary: query(() => ops.invoke('list-emoticon-library')),
        saveEmoticonItem: query((payload) => ops.invoke('save-emoticon-item', payload)),
        deleteEmoticonItem: query((id) => ops.invoke('delete-emoticon-item', id)),
        importEmoticonItems: query((payload) => ops.invoke('import-emoticon-items', payload)),
        listStudyLogDays: query((payload) => ops.invoke('list-study-log-days', payload)),
        listStudyLogEntries: query((payload) => ops.invoke('list-study-log-entries', payload)),
        getStudyLogEntry: query((payload) => ops.invoke('get-study-log-entry', payload)),
        getStudyDiaryDay: query((payload) => ops.invoke('get-study-diary-day', payload)),
        listStudyDiaryWallCards: query((payload) => ops.invoke('list-study-diary-wall-cards', payload)),
        getStudyDiaryWallDetail: query((payload) => ops.invoke('get-study-diary-wall-detail', payload)),
        searchStudyMemory: query((payload) => ops.invoke('search-study-memory', payload)),
        onAddFileToInput: subscription(ops.subscribe('add-file-to-input', (_event, filePath) => filePath)),
        watcherStart: query((filePath, agentId, topicId) => ops.invoke('watcher:start', filePath, agentId, topicId)),
        watcherStop: query(() => ops.invoke('watcher:stop')),
        onHistoryFileUpdated: subscription(ops.subscribe('watcher:history-updated', (_event, data) => data)),
    };
}

module.exports = {
    createSessionCatalog,
};
