const SHELL_KEYS = [
    'loadSettings',
    'saveSettings',
    'fetchModelServiceModels',
    'checkModelServiceProvider',
    'checkModelServiceHealth',
    'previewAgentBubbleThemePrompt',
    'previewFinalSystemPrompt',
    'saveAvatarColor',
    'readImageFromClipboard',
    'readTextFromClipboard',
    'minimizeWindow',
    'maximizeWindow',
    'unmaximizeWindow',
    'closeWindow',
    'openDevTools',
    'onWindowMaximized',
    'onWindowUnmaximized',
    'showImageContextMenu',
    'openImageViewer',
    'openImageInNewWindow',
    'openTextInNewWindow',
    'sendOpenExternalLink',
    'onThemeUpdated',
    'getCurrentTheme',
    'setTheme',
    'setThemeMode',
    'getPlatform',
];

const SESSION_KEYS = [
    'reportRendererFatalError',
    'getAgents',
    'getAgentConfig',
    'saveAgentConfig',
    'updateAgentConfig',
    'selectAvatar',
    'saveAvatar',
    'createAgent',
    'deleteAgent',
    'getActiveSystemPrompt',
    'getAgentTopics',
    'createNewTopicForAgent',
    'saveAgentTopicTitle',
    'deleteTopic',
    'getUnreadTopicCounts',
    'toggleTopicLock',
    'setTopicUnread',
    'getChatHistory',
    'saveChatHistory',
    'getOriginalMessageContent',
    'handleFilePaste',
    'selectFilesToSend',
    'getFileAsBase64',
    'getTextContent',
    'handleTextPasteAsFile',
    'handleFileDrop',
    'sendToVCP',
    'generateFollowUps',
    'generateTopicTitle',
    'onVCPStreamEvent',
    'interruptVcpRequest',
    'exportTopicAsMarkdown',
    'getEmoticonLibrary',
    'listEmoticonLibrary',
    'saveEmoticonItem',
    'deleteEmoticonItem',
    'importEmoticonItems',
    'listStudyLogDays',
    'listStudyLogEntries',
    'getStudyLogEntry',
    'getStudyDiaryDay',
    'listStudyDiaryWallCards',
    'getStudyDiaryWallDetail',
    'searchStudyMemory',
    'onAddFileToInput',
    'watcherStart',
    'watcherStop',
    'onHistoryFileUpdated',
];

const CONTENT_KEYS = [
    'searchNotes',
    'listKnowledgeBases',
    'createKnowledgeBase',
    'updateKnowledgeBase',
    'deleteKnowledgeBase',
    'importKnowledgeBaseFiles',
    'listKnowledgeBaseDocuments',
    'retryKnowledgeBaseDocument',
    'setTopicKnowledgeBase',
    'getTopicKnowledgeBase',
    'retrieveKnowledgeBaseContext',
    'searchKnowledgeBase',
    'getKnowledgeBaseRetrievalDebug',
    'getKnowledgeBaseDocumentViewData',
    'getKnowledgeBaseDocumentGuide',
    'generateKnowledgeBaseDocumentGuide',
    'listTopicNotes',
    'listAgentNotes',
    'saveTopicNote',
    'deleteTopicNote',
    'createNoteFromMessage',
    'createNoteFromSelection',
    'exportNoteAsAttachment',
];

const LITE_KEYS = Array.from(new Set([
    ...SHELL_KEYS,
    ...SESSION_KEYS,
    ...CONTENT_KEYS,
]));

const VIEWER_KEYS = [
    'minimizeWindow',
    'maximizeWindow',
    'unmaximizeWindow',
    'closeWindow',
    'openImageViewer',
    'sendOpenExternalLink',
    'onThemeUpdated',
    'getCurrentTheme',
    'getEmoticonLibrary',
];

module.exports = {
    SHELL_KEYS,
    SESSION_KEYS,
    CONTENT_KEYS,
    LITE_KEYS,
    VIEWER_KEYS,
    ROLE_API_NAMES: Object.freeze({
        lite: 'chatAPI',
        viewer: 'utilityAPI',
    }),
};
